### ISSUE TITLE
Use strong-typed parameters in Get-AlternateMailbox

### ISSUE THREAD

**Issue by Niehweune** [Mike-Crowley/Public-Scripts#1]
In [Get-AlternateMailboxes](https://github.com/Mike-Crowley/Public-Scripts/blob/9023d9171c477ae00a87facf371fbab783fc2cbc/Get-AlternateMailboxes.ps1#L28), you can use strong parameters to make sure the correct type is received by the function.
That way when you just call the function without parameters, PowerShell will correctly prompt for credentials (instead of asking for a string)

```
        [parameter(Mandatory=$true)][String]
        $SMTPAddress,
        [parameter(Mandatory=$true)][PSCredential]
        $Credential
        )
```

**Comment by Mike-Crowley** [comment]
suggestion has been incorporated (https://github.com/Mike-Crowley/Public-Scripts/commit/e56505fb0b3cdc8ef2a42e396fd56d0f0643f411) - thanks
