### ISSUE TITLE
Add X-AnchorMailbox header to Get-AlternateMailboxes

### ISSUE THREAD

**Issue by Niehweune** [Mike-Crowley/Public-Scripts#2]
Add X-AnchorMailbox header to make the request work.

```
    $Headers = @{
        ‘X-AnchorMailbox’ = $Credential.UserName
    }

   $webResponse [...] -Headers $Headers
```

**Comment by Mike-Crowley** [comment]
Thanks! I did mentioned this new requirement in the supporting blog [post](https://mikecrowley.us/2017/12/08/querying-msexchdelegatelistlink-in-exchange-online-with-powershell/), but that wasn't coordinated with the script transfer from TechNet.  Update has been pushed (https://github.com/Mike-Crowley/Public-Scripts/commit/e56505fb0b3cdc8ef2a42e396fd56d0f0643f411), though at this point, it needs to be completely retooled to support modern auth.
