### ISSUE TITLE
utf output

### ISSUE THREAD

**Issue by AthanPal** [Mike-Crowley/Public-Scripts#3]
on line #70  I have added  **-Encoding UTF8**

   $FilteredOutput | Sort TimeCreated | Export-Csv $FilePath -NoTypeInformation -Encoding UTF8

thank you !

Athan

**Comment by Mike-Crowley** [comment]
Thanks for your time and attention. I assume you're talking about

https://github.com/Mike-Crowley/Public-Scripts/blob/main/RDPConnectionParser.ps1

regarding your issue, is UTF8 your preference, or are you finding this to be a requirement? Can you elaborate?

**Comment by AthanPal** [comment]
Hello, 
it's a requirement for me, if I put UTF8 encoding , it works and i don't get  ?? char
![image](https://user-images.githubusercontent.com/31349946/173600996-573810a0-4bf8-4466-89af-5f63fc9d3db3.png)


thank you again !

**Comment by Mike-Crowley** [comment]
resolved via https://github.com/Mike-Crowley/Public-Scripts/commit/323a6fab48e9f451149e926b4b13eac8625e6928
