### ISSUE TITLE
Failing to run - possibly due to basic auth shutdown?

### ISSUE THREAD

**Issue by robhupf** [Mike-Crowley/Public-Scripts#4]
This is the error I get now.  I haven't changed my script for months and it was working.

Invoke-WebRequest : The remote server returned an error: (401) Unauthorized.

**Comment by Mike-Crowley** [comment]
You are asking about:

https://github.com/Mike-Crowley/Public-Scripts/blob/main/Get-AlternateMailboxes.ps1

Yes, as mentioned in the comments of the function itself, this does not support Modern Auth. As of late 2022, Microsoft's Greg Taylor says to use EWS or ActiveSync, for AutoDiscover, which means the server does the lookup for you, assuming your "client" is authorized. 

https://techcommunity.microsoft.com/t5/exchange-team-blog/basic-authentication-deprecation-in-exchange-online-what-s-next/bc-p/3678342/highlight/true#M34878

This means a simple AutoDiscover query is now only possible against the "v2" endpoint, which returns service URLs, but not mailbox details, like msExchDelegateListLink.

```
$Response = Invoke-WebRequest "https://outlook.office365.com/autodiscover/autodiscover.json/v1.0/mike@mikecrowley.us?Protocol=activesync" 
$Response.Content | ConvertFrom-Json
```
Returns:

```
Protocol   Url
--------   ---
activesync https://outlook.office365.com/Microsoft-Server-ActiveSync
```

I'll take a look at the authentication & EWS documentation to see if we can continue to have a single purpose tool for discovering msExchDelegateListLink, however it's looking like you might need administrative permissions in the tenant for application registration.

- https://learn.microsoft.com/en-us/exchange/client-developer/exchange-web-services/how-to-authenticate-an-ews-application-by-using-oauth
- https://learn.microsoft.com/en-us/exchange/client-developer/exchange-web-services/how-to-get-user-settings-from-exchange-by-using-autodiscover#set-up-to-get-user-settings
- https://github.com/gscales/Powershell-Scripts/blob/master/AutoDiscoverMap.ps1

This is a pretty old tool, and I'm not sure how/why people use it these days, so if you'd like to elaborate on your use case, it might motivate me to spend more time on this one.

**Comment by Mike-Crowley** [comment]
This "Resolution" paragraph suggests we may not need to use EWS and that we can indeed use Modern Auth (OAuth) with SOAP.

- https://learn.microsoft.com/en-us/exchange/troubleshoot/development/pox-autodiscover-not-supported-oauth-client-credentials-grant#resolution

Not sure how to do that yet, but if this is the case, we'd still need to register an app in Azure AD. If you already have Azure AD rights, you could also run this command, though it works in reverse (run against the delegate to find the master)

`Get-MailboxPermission 8134ad62-52a0-4335-ad5c-ab5d3627b186 -ReadFromDomainController | select DelegateListLink`

Pointed out by someone on my blog:
- https://mikecrowley.us/2017/12/08/querying-msexchdelegatelistlink-in-exchange-online-with-powershell/#comment-85360

**Comment by robhupf** [comment]
Hello Mike.  Thanks for looking into this.  I tried the powershell below and it shows the delegates when you run against the master, but not the other way around.  The primary use case for me is when someone reports not being able to see the delegated mailbox.  I could run your previous script to see all the auto-mapped mailboxes for the delegate.

 

It’s not the end of the world if it’s no longer possible, but it was a handy investigation tool.

**Comment by Mike-Crowley** [comment]
Yes, thats what I meant by having to run the other cmdlet in reverse. 

Based on what I've read, we should be able to do modern auth with the SOAP request, but that will take additional research. I'll try to get back to this when I have some additional time in the future.

**Comment by robhupf** [comment]
Thanks Mike. Understood.

**Comment by Mike-Crowley** [comment]
I've got it working.

https://mikecrowley.files.wordpress.com/2023/03/screenshot-2023-03-08-233555.png

You need to register an AAD App and give it Exchange Permissions, then include a token when requesting the url. I'll update the code to accept this method.

**Comment by Mike-Crowley** [comment]
Fixed: https://github.com/Mike-Crowley/Public-Scripts/commit/661df48db9f84d79a36afc963d794ed436f92927
